version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    environment: &env_app1
      RAILS_ENV: "production"
      BUNDLE_PATH: "/usr/local/bundle"
      BUNDLE_WITHOUT: "development test"
      BUNDLE_DEPLOYMENT: "1"
      RAILS_LOG_LEVEL: warn
      WEB_CONCURRENCY: 2
      RAILS_MAX_THREADS: 30
      RUBY_YJIT_ENABLE: 1
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1/rinha
      SECRET_KEY_BASE: xUZ2aYKI10TzUGY4juCkDIpip9LaDi8KOj0emd8HOHiFZh2zKT5sLXg+0/wzHfnw
      PORT: 9999
    depends_on:
      postgres:
        condition: service_healthy
    network_mode: host
    command: ["migrate_and_server"]
    deploy:
      resources:
        limits:
          cpus: '1.1'
          memory: '1.5GB'

  postgres:
    container_name: postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    network_mode: host
    volumes:
    - ./postgresql.conf:/etc/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 10
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '1.5GB'
