version: "3.8"

services:
  app1: &app1
    build:
      context: .
      dockerfile: Dockerfile
      target: release
    environment: &env_app1
      RAILS_ENV: "production"
      BUNDLE_PATH: "/usr/local/bundle"
      BUNDLE_WITHOUT: "development test"
      BUNDLE_DEPLOYMENT: "1"
      RAILS_LOG_LEVEL: error
      WEB_CONCURRENCY: 1
      RAILS_MAX_THREADS: 30
      DATABASE_POOL: 30
      RUBY_YJIT_ENABLE: 1
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1/rinha
      SECRET_KEY_BASE: xUZ2aYKI10TzUGY4juCkDIpip9LaDi8KOj0emd8HOHiFZh2zKT5sLXg+0/wzHfnw
      PORT: 9997
    depends_on:
    - postgres
    network_mode: host
    command: ["migrate_and_server"]
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: '0.5GB'

  app2:
    <<: *app1
    environment:
      <<: *env_app1
      PORT: 9998
    command: ["server"]

  nginx:
    image: nginx:alpine
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    command: ["nginx", "-g", "daemon off;"]
    depends_on:
    - app1
    - app2
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'

  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
    - 5432:5432
    network_mode: host
    volumes:
    - ./postgresql.conf:/etc/postgresql.conf
    command: ["postgres", "-c", "config_file=/etc/postgresql.conf"]
    deploy:
      resources:
        limits:
          cpus: '0.35'
          memory: '1.5GB'
